name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Using checkout action
        uses: actions/checkout@v2.1.0
      - name: Run a one line script
        run: echo Hello Rajesh, how are you!
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Using checkout action
        uses: actions/checkout@v2.1.0
      - name: Run a one line script
        run: echo Hello Rajesh
