name: Deploy to production
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Run Print command
        run: print "Hello Rajesh"
